### ISSUE TITLE
Error: When running bun init Prisma fails

### ISSUE THREAD

**Issue by idleite** [quenti-io/quenti#335]
When running bun init on bun 1.113 and Node 
`bun install v1.1.13 (bd6a6051)
  🚚 @next/swc-linux-x64-gnu... /home/harry/quenti/node_modules/prisma/build/index.js:867
    if (typeof process !== "undefined" && typeof process.stderr?.write !== "function") {
                                                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

error: postinstall script from "@quenti/prisma" exited with 1`

This happened on a fresh Ubuntu 22.04 Install and also happened when using node docker containers and bun docker containers

**Comment by Idleite** [comment]
After Looking more this seems to be an issue with prisma and not of quenti

**Comment by BatatiDE** [comment]
.take

**Comment by idleite** [comment]
not sure what the issue here was but it is now working.
